version: '3.8.15'

services:
  db:
    image: postgres:14.3-alpine3.15
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_flask



